In [1]:

import numpy as np
import sys
import time

In [3]:
arr = np.array([1,2,3,45,6,59])
a = np.empty((2,3))
a

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.2e-322, 3.0e-323, 2.9e-322]])

In [19]:

li = [i for i in range(1,10000000)]
arr1 = np.array(li)
sys.getsizeof(li)

89095160

In [9]:
#sizechart for array in  numpy
sys.getsizeof(np.array([1,2,3,4]))
#0 - 112
#1 - 120
#2 - 128

#80000104


144

In [17]:
#sizechart for list in python
sys.getsizeof([1,2,3])
#0 - 56
#1 - 64
#2 - 72
# 16 - 8 B
#89095160
(88-56)/3

10.666666666666666

In [20]:
list1 = [i for i in range(1,10000000)]
list2 = [i for i in range(1,10000000)]
list3 = [0 for i in range(1,10000000)]
start = time.time()
for i in range(len(list1)):
    list3[i] = list1[i] + list2[i]

end = time.time()
total = end - start
total

2.648948907852173

In [21]:
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
arr3 = arr1 + arr2

end = time.time()
total = end - start
total

0.08263158798217773

In [8]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [11]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [31]:
import random
np.random.seed(5)
arr = np.random.randint(1,10,5)

In [2]:
np.pi

3.141592653589793

In [3]:
angles = np.array([0,np.pi/2,np.pi,np.pi/4])

In [4]:
np.sin(angles)

array([0.00000000e+00, 1.00000000e+00, 1.22464680e-16, 7.07106781e-01])

In [5]:
np.cos(angles)

array([ 1.00000000e+00,  6.12323400e-17, -1.00000000e+00,  7.07106781e-01])

In [6]:
np.tan(angles)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16,  1.00000000e+00])

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
flt_arr = np.ravel(arr)
flt_arr[3] = 54
flt_arr
arr

array([[ 1,  2,  3],
       [54,  5,  6]])

In [17]:
arr1 = arr.flatten()
arr1[3] = 24
arr

array([[ 1,  2,  3],
       [54,  5,  6]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr = np.array([1,2,3,45,6,5,1,4,9])
re_arr = np.reshape(arr,(3,3))
re_arr

array([[ 1,  2,  3],
       [45,  6,  5],
       [ 1,  4,  9]])

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[7,8,9],[1,2,3]])
print(np.concatenate((arr,arr1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [24]:
np.stack((arr,arr1))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [29]:
arr = np.array([1,2,3,45,6,5,1,4])
np.split(arr,1)

[array([ 1,  2,  3, 45,  6,  5,  1,  4])]

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [7]:
np.transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
np.linalg.inv([[1,2],[5,6]])

array([[-1.5 ,  0.5 ],
       [ 1.25, -0.25]])